### ISSUE TITLE
Missing Animations

### ISSUE THREAD

**Issue by Bladeract** [RonaldCabrera/Queen-Cats-Dogs#3]
I am currently playing on a Fabric world, 1.19.2, and encounter something rather peculiar. Once I changed my cat over to the queen variant, the sitting and walking animations didn't seem to work anymore for the cat. Would you by chance have any recommendations or fixes?

**Comment by RonaldCabrera** [comment]
Are you running any resource packs / mods alongside Queen Cats & Dogs?

**Comment by RonaldCabrera** [comment]
Are you running any resource packs / mods alongside Queen Cats & Dogs?

**Comment by Sod1i** [comment]
Hello, I installed this mod in my assembly and also encountered the same problem.
Here is the list of mods I use
There are also shaders.
"makeup"
I do not use resource packs, only those that are added by mods[
![Screenshot_1](https://user-images.githubusercontent.com/121500778/209677356-4ff7f6bb-1136-4126-9dee-35569318c6cd.png)
![Screenshot_2](https://user-images.githubusercontent.com/121500778/209677361-bb7105a9-310d-4da6-b1f4-87d732ffeb2b.png)
![Screenshot_3](https://user-images.githubusercontent.com/121500778/209677362-7496f7f2-6258-4101-85c2-5e8471942c44.png)
![Screenshot_4](https://user-images.githubusercontent.com/121500778/209677364-8f071ca8-8f67-46fc-b67d-b048b5c35c0a.png)
](url)

**Comment by RonaldCabrera** [comment]
This issue has been finally fixed in 1.0.3, which will be released alongside the forge version, thanks a ton for reporting it!
