### ISSUE TITLE
1.0.5-1.19.2 crash during launch

### ISSUE THREAD

**Issue by Hexblood** [RonaldCabrera/Queen-Cats-Dogs#6]
Minecraft: 1.19.2
Fabric: 0.15.1
Fabric API: 0.77.0
Queen Cats & Dogs: 1.0.5

Issue:   After updating the mod from 1.0.4 to 1.0.5 my instance crashed before even generating a crash-report. 

Latest.log: https://pastebin.com/pJCDV9kw

Actions taken:   Downgraded back to 1.0.4 and the pack launches again.

**Comment by RonaldCabrera** [comment]
Seems like something related to the Queen Cow mixin may not be working properly under your current modpack, probably another mod modifying cows in some way?

**Comment by RonaldCabrera** [comment]
It's fixed, the mixin was overriding instead of injecting into the cow.
