### ISSUE TITLE
later version

### ISSUE THREAD

**Issue by Rogenar** [RonaldCabrera/Queen-Cats-Dogs#7]
Will there be an update to this mod for 1.20.4 and later versions?

**Comment by RonaldCabrera** [comment]
There are plans to do so, yes, currently there seems to be some weird drama going on between Forge and NeoForge? not entirely updated on that topic but the author I follow recommended to not update beyond 1.20.1 for now. (yes, when 1.21 releases I will indeed update, but that update is not near yet)

**Comment by Rogenar** [comment]
Thank you for the information.
