### ISSUE TITLE
Crashes before even opening Minecraft.

### ISSUE THREAD

**Issue by MegaComplainer** [RonaldCabrera/Queen-Cats-Dogs#9]
This is an issue with both curseforge and modrinth, I don't have any other mods installed (other than debugify, mod menu, and yet another config lib but issues started before installing any of them.) It won't even make a crash log so I have no idea what's wrong.

**Comment by RonaldCabrera** [comment]
But you did install geckolib, right?

**Comment by MegaComplainer** [comment]
Yes everything the mod needed was there.
